apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image
  namespace: skill-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-image
  template:
    metadata:
      labels:
        app: bad-image
    spec:
      containers:
        - name: app
          image: nginx:this-tag-does-not-exist
